openapi: 3.0.3
info:
  title: Kinnema
  version: 1.0.0
components:
  schemas:
    def-0:
      type: object
      title: url/auth
    def-1:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - username
        - email
      title: "#UserSchema"
    def-2:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
      title: "#LoginUserInputType"
    def-3:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - username
        - email
      title: "#LoginUserOutputType"
    def-4:
      type: object
      title: CreateUserInputType
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 5
        username:
          type: string
          minLength: 5
      required:
        - email
        - password
        - username
    def-5:
      type: object
      title: url/last_watched
    def-6:
      type: object
      title: lastWatchedSchemaOutputType
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        poster_path:
          type: string
        season:
          type: number
        episode:
          type: number
        isWatched:
          type: boolean
          nullable: true
        tmdbId:
          type: number
        userId:
          type: string
          format: uuid
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            username:
              type: string
            email:
              type: string
              format: email
          required:
            - id
            - username
            - email
          title: "#UserSchema"
      required:
        - id
        - name
        - poster_path
        - season
        - episode
        - tmdbId
        - userId
    def-7:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - username
        - email
      title: "#UserSchema"
    def-8:
      type: object
      title: lastWatchedCreateSchemaOutputType
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        poster_path:
          type: string
        season:
          type: number
        episode:
          type: number
        isWatched:
          type: boolean
          nullable: true
        tmdbId:
          type: number
        userId:
          type: string
          format: uuid
      required:
        - id
        - name
        - poster_path
        - season
        - episode
        - tmdbId
        - userId
    def-9:
      type: object
      title: lastWatchedCreateSchemaInputType
      properties:
        tmdbId:
          type: number
        name:
          type: string
        poster_path:
          type: string
        season:
          type: number
        episode:
          type: number
        isWatched:
          type: boolean
          nullable: true
        atSecond:
          type: number
      required:
        - tmdbId
        - name
        - poster_path
        - season
        - episode
        - atSecond
    def-10:
      type: object
      title: lastWatchedPatchSchemaOutputType
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        poster_path:
          type: string
        season:
          type: number
        episode:
          type: number
        isWatched:
          type: boolean
          nullable: true
        tmdbId:
          type: number
        userId:
          type: string
          format: uuid
      required:
        - id
        - name
        - poster_path
        - season
        - episode
        - tmdbId
        - userId
    def-11:
      type: object
      title: lastWatchedPatchSchemaInputType
      properties:
        season:
          type: number
          nullable: true
        episode:
          type: number
          nullable: true
        isWatched:
          type: boolean
          nullable: true
        tmdbId:
          type: number
          nullable: true
        name:
          type: string
          nullable: true
        poster_path:
          type: string
          nullable: true
        userId:
          type: string
          format: uuid
          nullable: true
        atSecond:
          type: number
          nullable: true
paths:
  /api/auth/:
    get:
      responses:
        "200":
          description: Default Response
  /api/auth/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: CreateUserInputType
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 5
                username:
                  type: string
                  minLength: 5
              required:
                - email
                - password
                - username
        required: true
      responses:
        "200":
          description: Default Response
  /api/auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  username:
                    type: string
                  email:
                    type: string
                    format: email
                required:
                  - id
                  - username
                  - email
  /api/auth/logout:
    delete:
      responses:
        "200":
          description: Default Response
  /api/last_watched/:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  title: lastWatchedSchemaOutputType
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    poster_path:
                      type: string
                    season:
                      type: number
                    episode:
                      type: number
                    isWatched:
                      type: boolean
                      nullable: true
                    tmdbId:
                      type: number
                    userId:
                      type: string
                      format: uuid
                    user:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        username:
                          type: string
                        email:
                          type: string
                          format: email
                      required:
                        - id
                        - username
                        - email
                  required:
                    - id
                    - name
                    - poster_path
                    - season
                    - episode
                    - tmdbId
                    - userId
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: lastWatchedCreateSchemaInputType
              properties:
                tmdbId:
                  type: number
                name:
                  type: string
                poster_path:
                  type: string
                season:
                  type: number
                episode:
                  type: number
                isWatched:
                  type: boolean
                  nullable: true
                atSecond:
                  type: number
              required:
                - tmdbId
                - name
                - poster_path
                - season
                - episode
                - atSecond
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                title: lastWatchedCreateSchemaOutputType
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  poster_path:
                    type: string
                  season:
                    type: number
                  episode:
                    type: number
                  isWatched:
                    type: boolean
                    nullable: true
                  tmdbId:
                    type: number
                  userId:
                    type: string
                    format: uuid
                required:
                  - id
                  - name
                  - poster_path
                  - season
                  - episode
                  - tmdbId
                  - userId
  /api/last_watched/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
          description: last watched id
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                title: lastWatchedSchemaOutputType
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  poster_path:
                    type: string
                  season:
                    type: number
                  episode:
                    type: number
                  isWatched:
                    type: boolean
                    nullable: true
                  tmdbId:
                    type: number
                  userId:
                    type: string
                    format: uuid
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      username:
                        type: string
                      email:
                        type: string
                        format: email
                    required:
                      - id
                      - username
                      - email
                required:
                  - id
                  - name
                  - poster_path
                  - season
                  - episode
                  - tmdbId
                  - userId
    patch:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: lastWatchedPatchSchemaInputType
              properties:
                season:
                  type: number
                  nullable: true
                episode:
                  type: number
                  nullable: true
                isWatched:
                  type: boolean
                  nullable: true
                tmdbId:
                  type: number
                  nullable: true
                name:
                  type: string
                  nullable: true
                poster_path:
                  type: string
                  nullable: true
                userId:
                  type: string
                  format: uuid
                  nullable: true
                atSecond:
                  type: number
                  nullable: true
      parameters:
        - schema:
            type: string
            format: uuid
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                title: lastWatchedPatchSchemaOutputType
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  poster_path:
                    type: string
                  season:
                    type: number
                  episode:
                    type: number
                  isWatched:
                    type: boolean
                    nullable: true
                  tmdbId:
                    type: number
                  userId:
                    type: string
                    format: uuid
                required:
                  - id
                  - name
                  - poster_path
                  - season
                  - episode
                  - tmdbId
                  - userId
