openapi: 3.0.3
info:
  title: Kinnema
  version: 1.0.0
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    def-0:
      type: object
      title: url/auth
    def-1:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - username
        - email
      title: "#UserSchema"
    def-2:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
      title: "#LoginUserInputType"
    def-3:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - username
        - email
      title: "#LoginUserOutputType"
    def-4:
      type: object
      title: CreateUserInputType
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 5
        username:
          type: string
          minLength: 5
      required:
        - email
        - password
        - username
    def-5:
      type: object
      title: url/favorite
paths:
  /api/auth/:
    get:
      responses:
        "200":
          description: Default Response
  /api/auth/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: CreateUserInputType
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 5
                username:
                  type: string
                  minLength: 5
              required:
                - email
                - password
                - username
        required: true
      responses:
        "200":
          description: Default Response
  /api/auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  username:
                    type: string
                  email:
                    type: string
                    format: email
                required:
                  - id
                  - username
                  - email
  /api/auth/logout:
    delete:
      responses:
        "200":
          description: Default Response
  /api/favorites/:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    poster_path:
                      type: string
                    tmdbId:
                      type: number
                    userId:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                  required:
                    - id
                    - name
                    - poster_path
                    - tmdbId
                    - userId
                    - createdAt
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                poster_path:
                  type: string
                tmdbId:
                  type: number
              required:
                - name
                - poster_path
                - tmdbId
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  poster_path:
                    type: string
                  tmdbId:
                    type: number
                  userId:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                required:
                  - id
                  - name
                  - poster_path
                  - tmdbId
                  - userId
                  - createdAt
  /api/favorites/{id}:
    delete:
      parameters:
        - schema:
            type: string
            format: uuid
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  poster_path:
                    type: string
                  tmdbId:
                    type: number
                  userId:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                required:
                  - id
                  - name
                  - poster_path
                  - tmdbId
                  - userId
                  - createdAt
  /openapi.yaml/:
    get:
      responses:
        "200":
          description: Default Response
