/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLastWatchedTmdbIdGet404Response
 */
export interface ApiLastWatchedTmdbIdGet404Response {
    /**
     * 
     * @type {string}
     * @memberof ApiLastWatchedTmdbIdGet404Response
     */
    error: string;
}

/**
 * Check if a given object implements the ApiLastWatchedTmdbIdGet404Response interface.
 */
export function instanceOfApiLastWatchedTmdbIdGet404Response(value: object): value is ApiLastWatchedTmdbIdGet404Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ApiLastWatchedTmdbIdGet404ResponseFromJSON(json: any): ApiLastWatchedTmdbIdGet404Response {
    return ApiLastWatchedTmdbIdGet404ResponseFromJSONTyped(json, false);
}

export function ApiLastWatchedTmdbIdGet404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLastWatchedTmdbIdGet404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function ApiLastWatchedTmdbIdGet404ResponseToJSON(json: any): ApiLastWatchedTmdbIdGet404Response {
    return ApiLastWatchedTmdbIdGet404ResponseToJSONTyped(json, false);
}

export function ApiLastWatchedTmdbIdGet404ResponseToJSONTyped(value?: ApiLastWatchedTmdbIdGet404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

