/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Def10
 */
export interface Def10 {
    /**
     * 
     * @type {string}
     * @memberof Def10
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Def10
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Def10
     */
    posterPath: string;
    /**
     * 
     * @type {number}
     * @memberof Def10
     */
    season: number;
    /**
     * 
     * @type {number}
     * @memberof Def10
     */
    episode: number;
    /**
     * 
     * @type {boolean}
     * @memberof Def10
     */
    isWatched?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof Def10
     */
    tmdbId: number;
    /**
     * 
     * @type {string}
     * @memberof Def10
     */
    userId: string;
}

/**
 * Check if a given object implements the Def10 interface.
 */
export function instanceOfDef10(value: object): value is Def10 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('posterPath' in value) || value['posterPath'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('episode' in value) || value['episode'] === undefined) return false;
    if (!('tmdbId' in value) || value['tmdbId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function Def10FromJSON(json: any): Def10 {
    return Def10FromJSONTyped(json, false);
}

export function Def10FromJSONTyped(json: any, ignoreDiscriminator: boolean): Def10 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'posterPath': json['poster_path'],
        'season': json['season'],
        'episode': json['episode'],
        'isWatched': json['isWatched'] == null ? undefined : json['isWatched'],
        'tmdbId': json['tmdbId'],
        'userId': json['userId'],
    };
}

export function Def10ToJSON(json: any): Def10 {
    return Def10ToJSONTyped(json, false);
}

export function Def10ToJSONTyped(value?: Def10 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'poster_path': value['posterPath'],
        'season': value['season'],
        'episode': value['episode'],
        'isWatched': value['isWatched'],
        'tmdbId': value['tmdbId'],
        'userId': value['userId'],
    };
}

