/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Def11
 */
export interface Def11 {
    /**
     * 
     * @type {number}
     * @memberof Def11
     */
    season?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Def11
     */
    episode?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Def11
     */
    isWatched?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof Def11
     */
    tmdbId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Def11
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Def11
     */
    posterPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Def11
     */
    userId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Def11
     */
    atSecond?: number | null;
}

/**
 * Check if a given object implements the Def11 interface.
 */
export function instanceOfDef11(value: object): value is Def11 {
    return true;
}

export function Def11FromJSON(json: any): Def11 {
    return Def11FromJSONTyped(json, false);
}

export function Def11FromJSONTyped(json: any, ignoreDiscriminator: boolean): Def11 {
    if (json == null) {
        return json;
    }
    return {
        
        'season': json['season'] == null ? undefined : json['season'],
        'episode': json['episode'] == null ? undefined : json['episode'],
        'isWatched': json['isWatched'] == null ? undefined : json['isWatched'],
        'tmdbId': json['tmdbId'] == null ? undefined : json['tmdbId'],
        'name': json['name'] == null ? undefined : json['name'],
        'posterPath': json['poster_path'] == null ? undefined : json['poster_path'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'atSecond': json['atSecond'] == null ? undefined : json['atSecond'],
    };
}

export function Def11ToJSON(json: any): Def11 {
    return Def11ToJSONTyped(json, false);
}

export function Def11ToJSONTyped(value?: Def11 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'season': value['season'],
        'episode': value['episode'],
        'isWatched': value['isWatched'],
        'tmdbId': value['tmdbId'],
        'name': value['name'],
        'poster_path': value['posterPath'],
        'userId': value['userId'],
        'atSecond': value['atSecond'],
    };
}

