/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Def7
 */
export interface Def7 {
    /**
     * 
     * @type {string}
     * @memberof Def7
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Def7
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Def7
     */
    email: string;
}

/**
 * Check if a given object implements the Def7 interface.
 */
export function instanceOfDef7(value: object): value is Def7 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function Def7FromJSON(json: any): Def7 {
    return Def7FromJSONTyped(json, false);
}

export function Def7FromJSONTyped(json: any, ignoreDiscriminator: boolean): Def7 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
    };
}

export function Def7ToJSON(json: any): Def7 {
    return Def7ToJSONTyped(json, false);
}

export function Def7ToJSONTyped(value?: Def7 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
    };
}

