/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiAuthLoginPost200Response } from './ApiAuthLoginPost200Response';
import {
    ApiAuthLoginPost200ResponseFromJSON,
    ApiAuthLoginPost200ResponseFromJSONTyped,
    ApiAuthLoginPost200ResponseToJSON,
    ApiAuthLoginPost200ResponseToJSONTyped,
} from './ApiAuthLoginPost200Response';

/**
 * 
 * @export
 * @interface LastWatchedSchemaOutputType
 */
export interface LastWatchedSchemaOutputType {
    /**
     * 
     * @type {string}
     * @memberof LastWatchedSchemaOutputType
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedSchemaOutputType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedSchemaOutputType
     */
    posterPath: string;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedSchemaOutputType
     */
    season: number;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedSchemaOutputType
     */
    episode: number;
    /**
     * 
     * @type {boolean}
     * @memberof LastWatchedSchemaOutputType
     */
    isWatched?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedSchemaOutputType
     */
    tmdbId: number;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedSchemaOutputType
     */
    atSecond: number;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedSchemaOutputType
     */
    userId: string;
    /**
     * 
     * @type {ApiAuthLoginPost200Response}
     * @memberof LastWatchedSchemaOutputType
     */
    user?: ApiAuthLoginPost200Response;
}

/**
 * Check if a given object implements the LastWatchedSchemaOutputType interface.
 */
export function instanceOfLastWatchedSchemaOutputType(value: object): value is LastWatchedSchemaOutputType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('posterPath' in value) || value['posterPath'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('episode' in value) || value['episode'] === undefined) return false;
    if (!('tmdbId' in value) || value['tmdbId'] === undefined) return false;
    if (!('atSecond' in value) || value['atSecond'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LastWatchedSchemaOutputTypeFromJSON(json: any): LastWatchedSchemaOutputType {
    return LastWatchedSchemaOutputTypeFromJSONTyped(json, false);
}

export function LastWatchedSchemaOutputTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastWatchedSchemaOutputType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'posterPath': json['poster_path'],
        'season': json['season'],
        'episode': json['episode'],
        'isWatched': json['isWatched'] == null ? undefined : json['isWatched'],
        'tmdbId': json['tmdbId'],
        'atSecond': json['atSecond'],
        'userId': json['userId'],
        'user': json['user'] == null ? undefined : ApiAuthLoginPost200ResponseFromJSON(json['user']),
    };
}

export function LastWatchedSchemaOutputTypeToJSON(json: any): LastWatchedSchemaOutputType {
    return LastWatchedSchemaOutputTypeToJSONTyped(json, false);
}

export function LastWatchedSchemaOutputTypeToJSONTyped(value?: LastWatchedSchemaOutputType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'poster_path': value['posterPath'],
        'season': value['season'],
        'episode': value['episode'],
        'isWatched': value['isWatched'],
        'tmdbId': value['tmdbId'],
        'atSecond': value['atSecond'],
        'userId': value['userId'],
        'user': ApiAuthLoginPost200ResponseToJSON(value['user']),
    };
}

