/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAuthLoginPost200Response
 */
export interface ApiAuthLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiAuthLoginPost200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthLoginPost200Response
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthLoginPost200Response
     */
    email: string;
}

/**
 * Check if a given object implements the ApiAuthLoginPost200Response interface.
 */
export function instanceOfApiAuthLoginPost200Response(value: object): value is ApiAuthLoginPost200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ApiAuthLoginPost200ResponseFromJSON(json: any): ApiAuthLoginPost200Response {
    return ApiAuthLoginPost200ResponseFromJSONTyped(json, false);
}

export function ApiAuthLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAuthLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
    };
}

export function ApiAuthLoginPost200ResponseToJSON(json: any): ApiAuthLoginPost200Response {
    return ApiAuthLoginPost200ResponseToJSONTyped(json, false);
}

export function ApiAuthLoginPost200ResponseToJSONTyped(value?: ApiAuthLoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
    };
}

