/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Def4
 */
export interface Def4 {
    /**
     * 
     * @type {string}
     * @memberof Def4
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Def4
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof Def4
     */
    username: string;
}

/**
 * Check if a given object implements the Def4 interface.
 */
export function instanceOfDef4(value: object): value is Def4 {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function Def4FromJSON(json: any): Def4 {
    return Def4FromJSONTyped(json, false);
}

export function Def4FromJSONTyped(json: any, ignoreDiscriminator: boolean): Def4 {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'username': json['username'],
    };
}

export function Def4ToJSON(json: any): Def4 {
    return Def4ToJSONTyped(json, false);
}

export function Def4ToJSONTyped(value?: Def4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'username': value['username'],
    };
}

