/* tslint:disable */
/* eslint-disable */
/**
 * Kinnema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LastWatchedPatchSchemaOutputType
 */
export interface LastWatchedPatchSchemaOutputType {
    /**
     * 
     * @type {string}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    posterPath: string;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    season: number;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    episode: number;
    /**
     * 
     * @type {boolean}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    isWatched?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    tmdbId: number;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    atSecond: number;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    totalSeconds: number;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    episodeName: string;
    /**
     * 
     * @type {number}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    network: number;
    /**
     * 
     * @type {string}
     * @memberof LastWatchedPatchSchemaOutputType
     */
    userId: string;
}

/**
 * Check if a given object implements the LastWatchedPatchSchemaOutputType interface.
 */
export function instanceOfLastWatchedPatchSchemaOutputType(value: object): value is LastWatchedPatchSchemaOutputType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('posterPath' in value) || value['posterPath'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('episode' in value) || value['episode'] === undefined) return false;
    if (!('tmdbId' in value) || value['tmdbId'] === undefined) return false;
    if (!('atSecond' in value) || value['atSecond'] === undefined) return false;
    if (!('totalSeconds' in value) || value['totalSeconds'] === undefined) return false;
    if (!('episodeName' in value) || value['episodeName'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LastWatchedPatchSchemaOutputTypeFromJSON(json: any): LastWatchedPatchSchemaOutputType {
    return LastWatchedPatchSchemaOutputTypeFromJSONTyped(json, false);
}

export function LastWatchedPatchSchemaOutputTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastWatchedPatchSchemaOutputType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'posterPath': json['poster_path'],
        'season': json['season'],
        'episode': json['episode'],
        'isWatched': json['isWatched'] == null ? undefined : json['isWatched'],
        'tmdbId': json['tmdbId'],
        'atSecond': json['atSecond'],
        'totalSeconds': json['totalSeconds'],
        'episodeName': json['episode_name'],
        'network': json['network'],
        'userId': json['userId'],
    };
}

export function LastWatchedPatchSchemaOutputTypeToJSON(json: any): LastWatchedPatchSchemaOutputType {
    return LastWatchedPatchSchemaOutputTypeToJSONTyped(json, false);
}

export function LastWatchedPatchSchemaOutputTypeToJSONTyped(value?: LastWatchedPatchSchemaOutputType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'poster_path': value['posterPath'],
        'season': value['season'],
        'episode': value['episode'],
        'isWatched': value['isWatched'],
        'tmdbId': value['tmdbId'],
        'atSecond': value['atSecond'],
        'totalSeconds': value['totalSeconds'],
        'episode_name': value['episodeName'],
        'network': value['network'],
        'userId': value['userId'],
    };
}

