/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as CollectionNetworkRouteImport } from './routes/collection.$network'
import { Route as DiziSlugTmdbIdRouteImport } from './routes/dizi.$slug.$tmdbId'
import { Route as DiziSlugTmdbIdSeasonChapterRouteImport } from './routes/dizi.$slug.$tmdbId.$season.$chapter'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const CollectionNetworkRoute = CollectionNetworkRouteImport.update({
  id: '/collection/$network',
  path: '/collection/$network',
  getParentRoute: () => rootRouteImport,
} as any)
const DiziSlugTmdbIdRoute = DiziSlugTmdbIdRouteImport.update({
  id: '/dizi/$slug/$tmdbId',
  path: '/dizi/$slug/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiziSlugTmdbIdSeasonChapterRoute =
  DiziSlugTmdbIdSeasonChapterRouteImport.update({
    id: '/$season/$chapter',
    path: '/$season/$chapter',
    getParentRoute: () => DiziSlugTmdbIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/collection/$network': typeof CollectionNetworkRoute
  '/': typeof LayoutIndexRoute
  '/dizi/$slug/$tmdbId': typeof DiziSlugTmdbIdRouteWithChildren
  '/dizi/$slug/$tmdbId/$season/$chapter': typeof DiziSlugTmdbIdSeasonChapterRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/collection/$network': typeof CollectionNetworkRoute
  '/': typeof LayoutIndexRoute
  '/dizi/$slug/$tmdbId': typeof DiziSlugTmdbIdRouteWithChildren
  '/dizi/$slug/$tmdbId/$season/$chapter': typeof DiziSlugTmdbIdSeasonChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/collection/$network': typeof CollectionNetworkRoute
  '/_layout/': typeof LayoutIndexRoute
  '/dizi/$slug/$tmdbId': typeof DiziSlugTmdbIdRouteWithChildren
  '/dizi/$slug/$tmdbId/$season/$chapter': typeof DiziSlugTmdbIdSeasonChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/favorites'
    | '/login'
    | '/plugins'
    | '/register'
    | '/search'
    | '/collection/$network'
    | '/'
    | '/dizi/$slug/$tmdbId'
    | '/dizi/$slug/$tmdbId/$season/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/login'
    | '/plugins'
    | '/register'
    | '/search'
    | '/collection/$network'
    | '/'
    | '/dizi/$slug/$tmdbId'
    | '/dizi/$slug/$tmdbId/$season/$chapter'
  id:
    | '__root__'
    | '/_layout'
    | '/favorites'
    | '/login'
    | '/plugins'
    | '/register'
    | '/search'
    | '/collection/$network'
    | '/_layout/'
    | '/dizi/$slug/$tmdbId'
    | '/dizi/$slug/$tmdbId/$season/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  PluginsRoute: typeof PluginsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CollectionNetworkRoute: typeof CollectionNetworkRoute
  DiziSlugTmdbIdRoute: typeof DiziSlugTmdbIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/collection/$network': {
      id: '/collection/$network'
      path: '/collection/$network'
      fullPath: '/collection/$network'
      preLoaderRoute: typeof CollectionNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dizi/$slug/$tmdbId': {
      id: '/dizi/$slug/$tmdbId'
      path: '/dizi/$slug/$tmdbId'
      fullPath: '/dizi/$slug/$tmdbId'
      preLoaderRoute: typeof DiziSlugTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dizi/$slug/$tmdbId/$season/$chapter': {
      id: '/dizi/$slug/$tmdbId/$season/$chapter'
      path: '/$season/$chapter'
      fullPath: '/dizi/$slug/$tmdbId/$season/$chapter'
      preLoaderRoute: typeof DiziSlugTmdbIdSeasonChapterRouteImport
      parentRoute: typeof DiziSlugTmdbIdRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DiziSlugTmdbIdRouteChildren {
  DiziSlugTmdbIdSeasonChapterRoute: typeof DiziSlugTmdbIdSeasonChapterRoute
}

const DiziSlugTmdbIdRouteChildren: DiziSlugTmdbIdRouteChildren = {
  DiziSlugTmdbIdSeasonChapterRoute: DiziSlugTmdbIdSeasonChapterRoute,
}

const DiziSlugTmdbIdRouteWithChildren = DiziSlugTmdbIdRoute._addFileChildren(
  DiziSlugTmdbIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  PluginsRoute: PluginsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CollectionNetworkRoute: CollectionNetworkRoute,
  DiziSlugTmdbIdRoute: DiziSlugTmdbIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
