/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as SettingsUpdatesRouteImport } from './routes/settings/updates'
import { Route as SettingsSubtitlesRouteImport } from './routes/settings/subtitles'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as CollectionNetworkRouteImport } from './routes/collection.$network'
import { Route as SettingsSyncIndexRouteImport } from './routes/settings/sync/index'
import { Route as SettingsSyncSetupRouteImport } from './routes/settings/sync/setup'
import { Route as SettingsSyncSyncIdRouteImport } from './routes/settings/sync/$syncId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const SettingsUpdatesRoute = SettingsUpdatesRouteImport.update({
  id: '/settings/updates',
  path: '/settings/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubtitlesRoute = SettingsSubtitlesRouteImport.update({
  id: '/settings/subtitles',
  path: '/settings/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionNetworkRoute = CollectionNetworkRouteImport.update({
  id: '/collection/$network',
  path: '/collection/$network',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncIndexRoute = SettingsSyncIndexRouteImport.update({
  id: '/settings/sync/',
  path: '/settings/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncSetupRoute = SettingsSyncSetupRouteImport.update({
  id: '/settings/sync/setup',
  path: '/settings/sync/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncSyncIdRoute = SettingsSyncSyncIdRouteImport.update({
  id: '/settings/sync/$syncId',
  path: '/settings/sync/$syncId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/collection/$network': typeof CollectionNetworkRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/subtitles': typeof SettingsSubtitlesRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/': typeof LayoutIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/sync/$syncId': typeof SettingsSyncSyncIdRoute
  '/settings/sync/setup': typeof SettingsSyncSetupRoute
  '/settings/sync': typeof SettingsSyncIndexRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/collection/$network': typeof CollectionNetworkRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/subtitles': typeof SettingsSubtitlesRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/': typeof LayoutIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/sync/$syncId': typeof SettingsSyncSyncIdRoute
  '/settings/sync/setup': typeof SettingsSyncSetupRoute
  '/settings/sync': typeof SettingsSyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/collection/$network': typeof CollectionNetworkRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/subtitles': typeof SettingsSubtitlesRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/sync/$syncId': typeof SettingsSyncSyncIdRoute
  '/settings/sync/setup': typeof SettingsSyncSetupRoute
  '/settings/sync/': typeof SettingsSyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/favorites'
    | '/login'
    | '/plugins'
    | '/register'
    | '/search'
    | '/collection/$network'
    | '/room/$roomId'
    | '/settings/language'
    | '/settings/subtitles'
    | '/settings/updates'
    | '/'
    | '/settings'
    | '/settings/sync/$syncId'
    | '/settings/sync/setup'
    | '/settings/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/login'
    | '/plugins'
    | '/register'
    | '/search'
    | '/collection/$network'
    | '/room/$roomId'
    | '/settings/language'
    | '/settings/subtitles'
    | '/settings/updates'
    | '/'
    | '/settings'
    | '/settings/sync/$syncId'
    | '/settings/sync/setup'
    | '/settings/sync'
  id:
    | '__root__'
    | '/_layout'
    | '/favorites'
    | '/login'
    | '/plugins'
    | '/register'
    | '/search'
    | '/collection/$network'
    | '/room/$roomId'
    | '/settings/language'
    | '/settings/subtitles'
    | '/settings/updates'
    | '/_layout/'
    | '/settings/'
    | '/settings/sync/$syncId'
    | '/settings/sync/setup'
    | '/settings/sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  PluginsRoute: typeof PluginsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  CollectionNetworkRoute: typeof CollectionNetworkRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsSubtitlesRoute: typeof SettingsSubtitlesRoute
  SettingsUpdatesRoute: typeof SettingsUpdatesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsSyncSyncIdRoute: typeof SettingsSyncSyncIdRoute
  SettingsSyncSetupRoute: typeof SettingsSyncSetupRoute
  SettingsSyncIndexRoute: typeof SettingsSyncIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/settings/updates': {
      id: '/settings/updates'
      path: '/settings/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof SettingsUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subtitles': {
      id: '/settings/subtitles'
      path: '/settings/subtitles'
      fullPath: '/settings/subtitles'
      preLoaderRoute: typeof SettingsSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$network': {
      id: '/collection/$network'
      path: '/collection/$network'
      fullPath: '/collection/$network'
      preLoaderRoute: typeof CollectionNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync/': {
      id: '/settings/sync/'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync/setup': {
      id: '/settings/sync/setup'
      path: '/settings/sync/setup'
      fullPath: '/settings/sync/setup'
      preLoaderRoute: typeof SettingsSyncSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync/$syncId': {
      id: '/settings/sync/$syncId'
      path: '/settings/sync/$syncId'
      fullPath: '/settings/sync/$syncId'
      preLoaderRoute: typeof SettingsSyncSyncIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  PluginsRoute: PluginsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  CollectionNetworkRoute: CollectionNetworkRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsSubtitlesRoute: SettingsSubtitlesRoute,
  SettingsUpdatesRoute: SettingsUpdatesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsSyncSyncIdRoute: SettingsSyncSyncIdRoute,
  SettingsSyncSetupRoute: SettingsSyncSetupRoute,
  SettingsSyncIndexRoute: SettingsSyncIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
